name: User Workflow

on: 
    workflow_dispatch:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
#             - name: Checkout Repo
#               uses: actions/checkout@v3
#               with: 
#                 persist-credentials: false
              
            - name: Reusable Workflow
              uses: enteraga6/cc_bazel_test/blob/main/internal/example@main
              with:
                who-to-greet: 'Noah'
